// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIjpY6u6t4Sv4aiejRw0BtMYWLp3TBJH0',
    appId: '1:619867177582:web:0abfdb8bbe136b3ac0dc7f',
    messagingSenderId: '619867177582',
    projectId: 'gpsdb-4f8ff',
    authDomain: 'gpsdb-4f8ff.firebaseapp.com',
    storageBucket: 'gpsdb-4f8ff.appspot.com',
    measurementId: 'G-9DE911Q9GK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUQy2fmrwOcWjqqgXmmIwi2mQcswaAzgM',
    appId: '1:619867177582:android:e2eaa0222e1a314dc0dc7f',
    messagingSenderId: '619867177582',
    projectId: 'gpsdb-4f8ff',
    storageBucket: 'gpsdb-4f8ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtEZtdEDxwJhTut0cIzwi3EdwDy9Z5fbA',
    appId: '1:619867177582:ios:4d00da047274898fc0dc7f',
    messagingSenderId: '619867177582',
    projectId: 'gpsdb-4f8ff',
    storageBucket: 'gpsdb-4f8ff.appspot.com',
    iosClientId: '619867177582-94171kbdehnv5o82jtt966ac6bii98go.apps.googleusercontent.com',
    iosBundleId: 'com.flutter.proj',
  );
}
